### ISSUE TITLE
Ignore previous messages in mailing list

### ISSUE THREAD

**Issue by aureleoules** [bitcoinsearch/scraper#1]
Should be able to just ignore lines that start with `>`.

Attach original mail to replies to give more context?

**Comment by adamjonas** [comment]
I wonder if we flag the original post and only show that in the displayed results unless someone has specifically asked for an author or other qualifying facet

**Comment by adamjonas** [comment]
In thinking this over, I think we can build a decent interface for this on the front end if we have the attribute of whether an email was the original post or a reply.

Can we reindex with that information using the type field?

**Comment by aureleoules** [comment]
I've looked into different approaches to determine the type of post:

- Parse the mail content and look for quoted content (`>`)
	The problem is that it appears people quote emails differently, sometimes at the top, sometimes at the bottom. And a new thread can also contain quoted text.

- Parse Previous Message and Next message mail subjects
![image](https://user-images.githubusercontent.com/22493292/214080983-413172a9-ddeb-47b9-8ba9-336b30b26d25.png)
	It is only on a per-month basis, so reply to a thread created from the last month will be considered a thread too.

- Look for header tags in the mail served by the mailing list archive: there is none.
	`view-source:https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-July/020791.html`
	I also looked into the Gzip'd dumps and I can't find any useful tag.

Do you have other ideas in mind?

**Comment by adamjonas** [comment]
The earliest timestamp is the original post, right? Scrape them all then loop through and add OP type to earliest timestamp and reply to all the others.
