### ISSUE TITLE
add addition elasticsearch scrapers

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/scraper#17]
https://github.com/bitcoinsearch/scraper/pull/16 sets up new scrapers to push to our elasticsearch cluster (rather than the app search which we have been using to date)

We need to create similar scrapers for:
 - https://github.com/bitcoinsearch/scraper/tree/master/mailing-list
 - https://github.com/bitcoinsearch/scraper/tree/master/bitcoinops
 - https://github.com/bitcoinsearch/scraper/tree/master/bitcointranscripts
 - https://github.com/bitcoinsearch/scraper/tree/master/bitcointalk

Let's take the approach of building a separate scraper rather than replacing the currently running ones so that we can gradually transfer instead of needing to do it all at once.

**Comment by adamjonas** [comment]
The mailing lists are good and bitcoinops is (partially) indexed. Transcripts and bitcoin talk are still not.

Note that bitcointalk will have to be indexed manually to start because it is so big and will timeout.

**Comment by kouloumos** [comment]
We now have scrapers for the aforementioned sources. All sources/scrapers can be found in the [README](https://github.com/bitcoinsearch/scraper/blob/master/README.md)
