### ISSUE TITLE
Pull thumbnails from youtube for transcripts from btctranscript

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/scraper#2]
Fetch and store youtube thumbnails for transcripts with youtube urls in the media tag

**Comment by aureleoules** [comment]
The thumbnail url can be determined in the front-end directly. I don't think we should add it to the Elasticsearch database.
`https://i3.ytimg.com/vi/[YOUTUBE_ID]/maxresdefault.jpg`
