### ISSUE TITLE
Parsing author names

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcoinsearch/scraper#67]
Some author names have slightly different characters during scraping and parsing. And they end up as separate entities in the index.
Example `josibake`

<img width="199" alt="Screenshot 2024-05-27 at 2 18 33 PM" src="https://github.com/bitcoinsearch/scraper/assets/62019510/ead1c3de-df51-4edb-9d24-730724eb7daa">

![image](https://github.com/bitcoinsearch/scraper/assets/62019510/0a281ff2-1a91-4555-b466-53132c0b1eaa)
<img width="214" alt="Screenshot 2024-05-27 at 2 39 02 PM" src="https://github.com/bitcoinsearch/scraper/assets/62019510/3f011b6d-8ce8-4445-b693-373cefc4e490">

**Comment by kouloumos** [comment]
@Emmanuel-Develops, are the examples that you provided the only ones with this issue? 
A quick fix that you could do on your end is to create a mapping between the different versions of the name.

But you are right that this needs to be fixed here.

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops, are the examples that you provided the only ones with this issue? A quick fix that you could do on your end is to create a mapping between the different versions of the name.
> 
> But you are right that this needs to be fixed here.

no, it is not an exhaustive list by any means. Reconciling on the FE gets complicated as they will all display as the same reconciled string separately (for example 3 correct josibake shown in authors filter)
