### ISSUE TITLE
Google Programmable Search to help ranking factors

### ISSUE THREAD

**Issue by fjahr** [bitcoinsearch/scraper#9]
Hey, very cool project! Did you look into Google Programmable Search (https://programmablesearchengine.google.com/about/) and compare its results to yours yet?

In case not, I created one here that only has the same sources you seem to be scraping already: https://cse.google.com/cse?cx=30421d2f1606340f5

Compared to a Google programmable search on the same sources it seems to prefer SE a lot while Optech isn't very popular. Probably because backlinks are not a factor. Maybe you could run and scrape a GPS on the same pages and use it as input on ranking factors? Some people may not like a "googlified" result, so maybe it could be optional as well.

**Comment by adamjonas** [comment]
Programmable search has a domain limit to it. We considered using it as the backend to start but we'd have to get off as we grew so went with elasticsearch instead.

**Comment by adamjonas** [comment]
Given the thumbs up, closing for now.
